# Generated by Django 5.1.5 on 2025-03-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
