# Generated by Django 5.1.5 on 2025-02-05 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0003_alter_board_name'),
        ('tasks_app', '0002_remove_task_status_task_board_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='board_list',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='boards_app.boardlist'),
        ),
    ]
