# Generated by Django 5.1.5 on 2025-02-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0005_alter_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color_brightness',
            field=models.BooleanField(default=False),
        ),
    ]
