# Generated by Django 5.1.5 on 2025-02-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0006_category_color_brightness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color_brightness',
            field=models.BooleanField(),
        ),
    ]
