# Generated by Django 5.1.5 on 2025-02-10 17:56

import utils.auxiliary_functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0008_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default=utils.auxiliary_functions.generate_random_color, max_length=7, validators=[utils.auxiliary_functions.validate_hex_color]),
        ),
    ]
