# Generated by Django 5.1.5 on 2025-04-04 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0010_alter_category_color_brightness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='deletable',
            new_name='is_deletable',
        ),
    ]
