# Generated by Django 5.1.5 on 2025-02-04 20:39

import django.core.validators
import utils.auxiliary_functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number. Only numbers, spaces, and the symbols +, -, /, and () are allowed.', regex='^[0-9+\\-\\(\\)\\/\\s]*$')])),
                ('color', models.CharField(default=utils.auxiliary_functions.generate_random_color, max_length=7)),
            ],
        ),
    ]
