# Generated by Django 5.1.5 on 2025-02-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0004_contact_color_brightness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='color_brightness',
            field=models.BooleanField(),
        ),
    ]
