# Generated by Django 5.1.5 on 2025-02-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0002_board_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
